# Generated by Django 3.2.4 on 2021-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='label',
            field=models.CharField(default='General-Awareness', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
