# Generated by Django 3.2.4 on 2021-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210620_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upload',
            field=models.ImageField(default='logo.jpg', upload_to='fileupload'),
        ),
    ]
