# Generated by Django 3.2.4 on 2021-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blogpost_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='upload',
            field=models.ImageField(default='logo.jpg', upload_to='media'),
        ),
    ]
