# Generated by Django 3.2.4 on 2021-06-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210622_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='age',
        ),
    ]
